apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: interviewmaster-hpa
  labels:
    app: interviewmaster
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: interviewmaster-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 