apiVersion: v1
kind: Service
metadata:
  name: interviewmaster-service
  labels:
    app: interviewmaster
spec:
  selector:
    app: interviewmaster
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP 