apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: interviewmaster-servicemonitor
  labels:
    app: interviewmaster
spec:
  selector:
    matchLabels:
      app: interviewmaster
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  namespaceSelector:
    any: true 